# -*- coding: utf-8 -*-
require_relative '../foto_festival'


class FotoUtil
  # 佛历工具

  # 观音斋日期
  DAY_ZHAI_GUAN_YIN = ["1-8", "2-7", "2-9", "2-19", "3-3", "3-6", "3-13", "4-22", "5-3", "5-17", "6-16", "6-18", "6-19", "6-23", "7-13", "8-16", "9-19", "9-23", "10-2", "11-19", "11-24", "12-25"]

  # 27星宿，佛教从印度传入中国，印度把28星宿改为27星宿，把牛宿(牛金牛)纳入了女宿(女土蝠)。
  XIU_27 = ["角", "亢", "氐", "房", "心", "尾", "箕", "斗", "女", "虚", "危", "室", "壁", "奎", "娄", "胃", "昴", "毕", "觜", "参", "井", "鬼", "柳", "星", "张", "翼", "轸"]

  # 每月初一的27星宿偏移
  XIU_OFFSET = [11, 13, 15, 17, 19, 21, 24, 0, 2, 4, 7, 9]

  def self.getXiu(month, day)
    # 获取27星宿
    # :param month: 佛历月
    # :param day: 佛历日
    # :return: 星宿
    FotoUtil::XIU_27[(FotoUtil::XIU_OFFSET[month.abs-1] + day - 1) % FotoUtil::XIU_27.length]
  end

  DJ_PRIVATE = "犯者夺纪"
  JS_PRIVATE = "犯者减寿"
  SS_PRIVATE = "犯者损寿"
  XL_PRIVATE = "犯者削禄夺纪"
  JW_PRIVATE = "犯者三年内夫妇俱亡"

  Y_PRIVATE = FotoFestival.new("杨公忌")
  T_PRIVATE = FotoFestival.new("四天王巡行", "", true)
  D_PRIVATE = FotoFestival.new("斗降", DJ_PRIVATE, true)
  S_PRIVATE = FotoFestival.new("月朔", DJ_PRIVATE, true)
  W_PRIVATE = FotoFestival.new("月望", DJ_PRIVATE, true)
  H_PRIVATE = FotoFestival.new("月晦", JS_PRIVATE, true)
  L_PRIVATE = FotoFestival.new("雷斋日", JS_PRIVATE, true)
  J_PRIVATE = FotoFestival.new("九毒日", "犯者夭亡，奇祸不测")
  R_PRIVATE = FotoFestival.new("人神在阴", "犯者得病", true, "宜先一日即戒")
  M_PRIVATE = FotoFestival.new("司命奏事", JS_PRIVATE, true, "如月小，即戒廿九")
  HH_PRIVATE = FotoFestival.new("月晦", JS_PRIVATE, true, "如月小，即戒廿九")

  # 日期对应的非正式节日
  FESTIVAL = {
    "1-1" => [FotoFestival.new("天腊，玉帝校世人神气禄命", XL_PRIVATE), S_PRIVATE],
    "1-3" => [FotoFestival.new("万神都会", DJ_PRIVATE), D_PRIVATE],
    "1-5" => [FotoFestival.new("五虚忌")],
    "1-6" => [FotoFestival.new("六耗忌"), L_PRIVATE],
    "1-7" => [FotoFestival.new("上会日", SS_PRIVATE)],
    "1-8" => [FotoFestival.new("五殿阎罗天子诞", DJ_PRIVATE), T_PRIVATE],
    "1-9" => [FotoFestival.new("玉皇上帝诞", DJ_PRIVATE)],
    "1-13" => [Y_PRIVATE],
    "1-14" => [FotoFestival.new("三元降", JS_PRIVATE), T_PRIVATE],
    "1-15" => [FotoFestival.new("三元降", JS_PRIVATE), FotoFestival.new("上元神会", DJ_PRIVATE), W_PRIVATE, T_PRIVATE],
    "1-16" => [FotoFestival.new("三元降", JS_PRIVATE)],
    "1-19" => [FotoFestival.new("长春真人诞")],
    "1-23" => [FotoFestival.new("三尸神奏事"), T_PRIVATE],
    "1-25" => [H_PRIVATE, FotoFestival.new("天地仓开日", "犯者损寿，子带疾")],
    "1-27" => [D_PRIVATE],
    "1-28" => [R_PRIVATE],
    "1-29" => [T_PRIVATE],
    "1-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "2-1" => [FotoFestival.new("一殿秦广王诞", DJ_PRIVATE), S_PRIVATE],
    "2-2" => [FotoFestival.new("万神都会", DJ_PRIVATE), FotoFestival.new("福德土地正神诞", "犯者得祸")],
    "2-3" => [FotoFestival.new("文昌帝君诞", XL_PRIVATE), D_PRIVATE],
    "2-6" => [FotoFestival.new("东华帝君诞"), L_PRIVATE],
    "2-8" => [FotoFestival.new("释迦牟尼佛出家", DJ_PRIVATE), FotoFestival.new("三殿宋帝王诞", DJ_PRIVATE), FotoFestival.new("张大帝诞", DJ_PRIVATE), T_PRIVATE],
    "2-11" => [Y_PRIVATE],
    "2-14" => [T_PRIVATE],
    "2-15" => [FotoFestival.new("释迦牟尼佛涅槃", XL_PRIVATE), FotoFestival.new("太上老君诞", XL_PRIVATE), FotoFestival.new("月望", XL_PRIVATE, true), T_PRIVATE],
    "2-17" => [FotoFestival.new("东方杜将军诞")],
    "2-18" => [FotoFestival.new("四殿五官王诞", XL_PRIVATE), FotoFestival.new("至圣先师孔子讳辰", XL_PRIVATE)],
    "2-19" => [FotoFestival.new("观音大士诞", DJ_PRIVATE)],
    "2-21" => [FotoFestival.new("普贤菩萨诞")],
    "2-23" => [T_PRIVATE],
    "2-25" => [H_PRIVATE],
    "2-27" => [D_PRIVATE],
    "2-28" => [R_PRIVATE],
    "2-29" => [T_PRIVATE],
    "2-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "3-1" => [FotoFestival.new("二殿楚江王诞", DJ_PRIVATE), S_PRIVATE],
    "3-3" => [FotoFestival.new("玄天上帝诞", DJ_PRIVATE), D_PRIVATE],
    "3-6" => [L_PRIVATE],
    "3-8" => [FotoFestival.new("六殿卞城王诞", DJ_PRIVATE), T_PRIVATE],
    "3-9" => [FotoFestival.new("牛鬼神出", "犯者产恶胎"), Y_PRIVATE],
    "3-12" => [FotoFestival.new("中央五道诞")],
    "3-14" => [T_PRIVATE],
    "3-15" => [FotoFestival.new("昊天上帝诞", DJ_PRIVATE), FotoFestival.new("玄坛诞", DJ_PRIVATE), W_PRIVATE, T_PRIVATE],
    "3-16" => [FotoFestival.new("准提菩萨诞", DJ_PRIVATE)],
    "3-19" => [FotoFestival.new("中岳大帝诞"), FotoFestival.new("后土娘娘诞"), FotoFestival.new("三茅降")],
    "3-20" => [FotoFestival.new("天地仓开日", SS_PRIVATE), FotoFestival.new("子孙娘娘诞")],
    "3-23" => [T_PRIVATE],
    "3-25" => [H_PRIVATE],
    "3-27" => [FotoFestival.new("七殿泰山王诞"), D_PRIVATE],
    "3-28" => [R_PRIVATE, FotoFestival.new("苍颉至圣先师诞", XL_PRIVATE), FotoFestival.new("东岳大帝诞")],
    "3-29" => [T_PRIVATE],
    "3-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "4-1" => [FotoFestival.new("八殿都市王诞", DJ_PRIVATE), S_PRIVATE],
    "4-3" => [D_PRIVATE],
    "4-4" => [FotoFestival.new("万神善会", "犯者失瘼夭胎"), FotoFestival.new("文殊菩萨诞")],
    "4-6" => [L_PRIVATE],
    "4-7" => [FotoFestival.new("南斗、北斗、西斗同降", JS_PRIVATE), Y_PRIVATE],
    "4-8" => [FotoFestival.new("释迦牟尼佛诞", DJ_PRIVATE), FotoFestival.new("万神善会", "犯者失瘼夭胎"), FotoFestival.new("善恶童子降", "犯者血死"), FotoFestival.new("九殿平等王诞"), T_PRIVATE],
    "4-14" => [FotoFestival.new("纯阳祖师诞", JS_PRIVATE), T_PRIVATE],
    "4-15" => [W_PRIVATE, FotoFestival.new("钟离祖师诞"), T_PRIVATE],
    "4-16" => [FotoFestival.new("天地仓开日", SS_PRIVATE)],
    "4-17" => [FotoFestival.new("十殿转轮王诞", DJ_PRIVATE)],
    "4-18" => [FotoFestival.new("天地仓开日", SS_PRIVATE), FotoFestival.new("紫徽大帝诞", SS_PRIVATE)],
    "4-20" => [FotoFestival.new("眼光圣母诞")],
    "4-23" => [T_PRIVATE],
    "4-25" => [H_PRIVATE],
    "4-27" => [D_PRIVATE],
    "4-28" => [R_PRIVATE],
    "4-29" => [T_PRIVATE],
    "4-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "5-1" => [FotoFestival.new("南极长生大帝诞", DJ_PRIVATE), S_PRIVATE],
    "5-3" => [D_PRIVATE],
    "5-5" => [FotoFestival.new("地腊", XL_PRIVATE), FotoFestival.new("五帝校定生人官爵", XL_PRIVATE), J_PRIVATE, Y_PRIVATE],
    "5-6" => [J_PRIVATE, L_PRIVATE],
    "5-7" => [J_PRIVATE],
    "5-8" => [FotoFestival.new("南方五道诞"), T_PRIVATE],
    "5-11" => [FotoFestival.new("天地仓开日", SS_PRIVATE), FotoFestival.new("天下都城隍诞")],
    "5-12" => [FotoFestival.new("炳灵公诞")],
    "5-13" => [FotoFestival.new("关圣降", XL_PRIVATE)],
    "5-14" => [FotoFestival.new("夜子时为天地交泰", JW_PRIVATE), T_PRIVATE],
    "5-15" => [W_PRIVATE, J_PRIVATE, T_PRIVATE],
    "5-16" => [FotoFestival.new("九毒日", JW_PRIVATE), FotoFestival.new("天地元气造化万物之辰", JW_PRIVATE)],
    "5-17" => [J_PRIVATE],
    "5-18" => [FotoFestival.new("张天师诞")],
    "5-22" => [FotoFestival.new("孝娥神诞", DJ_PRIVATE)],
    "5-23" => [T_PRIVATE],
    "5-25" => [J_PRIVATE, H_PRIVATE],
    "5-26" => [J_PRIVATE],
    "5-27" => [J_PRIVATE, D_PRIVATE],
    "5-28" => [R_PRIVATE],
    "5-29" => [T_PRIVATE],
    "5-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "6-1" => [S_PRIVATE],
    "6-3" => [FotoFestival.new("韦驮菩萨圣诞"), D_PRIVATE, Y_PRIVATE],
    "6-5" => [FotoFestival.new("南赡部洲转大轮", SS_PRIVATE)],
    "6-6" => [FotoFestival.new("天地仓开日", SS_PRIVATE), L_PRIVATE],
    "6-8" => [T_PRIVATE],
    "6-10" => [FotoFestival.new("金粟如来诞")],
    "6-14" => [T_PRIVATE],
    "6-15" => [W_PRIVATE, T_PRIVATE],
    "6-19" => [FotoFestival.new("观世音菩萨成道", DJ_PRIVATE)],
    "6-23" => [FotoFestival.new("南方火神诞", "犯者遭回禄"), T_PRIVATE],
    "6-24" => [FotoFestival.new("雷祖诞", XL_PRIVATE), FotoFestival.new("关帝诞", XL_PRIVATE)],
    "6-25" => [H_PRIVATE],
    "6-27" => [D_PRIVATE],
    "6-28" => [R_PRIVATE],
    "6-29" => [T_PRIVATE],
    "6-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "7-1" => [S_PRIVATE, Y_PRIVATE],
    "7-3" => [D_PRIVATE],
    "7-5" => [FotoFestival.new("中会日", SS_PRIVATE, false, "一作初七")],
    "7-6" => [L_PRIVATE],
    "7-7" => [FotoFestival.new("道德腊", XL_PRIVATE), FotoFestival.new("五帝校生人善恶", XL_PRIVATE), FotoFestival.new("魁星诞", XL_PRIVATE)],
    "7-8" => [T_PRIVATE],
    "7-10" => [FotoFestival.new("阴毒日", "", false, "大忌")],
    "7-12" => [FotoFestival.new("长真谭真人诞")],
    "7-13" => [FotoFestival.new("大势至菩萨诞", JS_PRIVATE)],
    "7-14" => [FotoFestival.new("三元降", JS_PRIVATE), T_PRIVATE],
    "7-15" => [W_PRIVATE, FotoFestival.new("三元降", DJ_PRIVATE), FotoFestival.new("地官校籍", DJ_PRIVATE), T_PRIVATE],
    "7-16" => [FotoFestival.new("三元降", JS_PRIVATE)],
    "7-18" => [FotoFestival.new("西王母诞", DJ_PRIVATE)],
    "7-19" => [FotoFestival.new("太岁诞", DJ_PRIVATE)],
    "7-22" => [FotoFestival.new("增福财神诞", XL_PRIVATE)],
    "7-23" => [T_PRIVATE],
    "7-25" => [H_PRIVATE],
    "7-27" => [D_PRIVATE],
    "7-28" => [R_PRIVATE],
    "7-29" => [Y_PRIVATE, T_PRIVATE],
    "7-30" => [FotoFestival.new("地藏菩萨诞", DJ_PRIVATE), HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "8-1" => [S_PRIVATE, FotoFestival.new("许真君诞")],
    "8-3" => [D_PRIVATE, FotoFestival.new("北斗诞", XL_PRIVATE), FotoFestival.new("司命灶君诞", "犯者遭回禄")],
    "8-5" => [FotoFestival.new("雷声大帝诞", DJ_PRIVATE)],
    "8-6" => [L_PRIVATE],
    "8-8" => [T_PRIVATE],
    "8-10" => [FotoFestival.new("北斗大帝诞")],
    "8-12" => [FotoFestival.new("西方五道诞")],
    "8-14" => [T_PRIVATE],
    "8-15" => [W_PRIVATE, FotoFestival.new("太明朝元", "犯者暴亡", false, "宜焚香守夜"), T_PRIVATE],
    "8-16" => [FotoFestival.new("天曹掠刷真君降", "犯者贫夭")],
    "8-18" => [FotoFestival.new("天人兴福之辰", "", false, "宜斋戒，存想吉事")],
    "8-23" => [FotoFestival.new("汉恒候张显王诞"), T_PRIVATE],
    "8-24" => [FotoFestival.new("灶君夫人诞")],
    "8-25" => [H_PRIVATE],
    "8-27" => [D_PRIVATE, FotoFestival.new("至圣先师孔子诞", XL_PRIVATE), Y_PRIVATE],
    "8-28" => [R_PRIVATE, FotoFestival.new("四天会事")],
    "8-29" => [T_PRIVATE],
    "8-30" => [FotoFestival.new("诸神考校", "犯者夺算"), HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "9-1" => [S_PRIVATE, FotoFestival.new("南斗诞", XL_PRIVATE), FotoFestival.new("北斗九星降世", DJ_PRIVATE, false, "此九日俱宜斋戒")],
    "9-3" => [D_PRIVATE, FotoFestival.new("五瘟神诞")],
    "9-6" => [L_PRIVATE],
    "9-8" => [T_PRIVATE],
    "9-9" => [FotoFestival.new("斗母诞", XL_PRIVATE), FotoFestival.new("酆都大帝诞"), FotoFestival.new("玄天上帝飞升")],
    "9-10" => [FotoFestival.new("斗母降", DJ_PRIVATE)],
    "9-11" => [FotoFestival.new("宜戒")],
    "9-13" => [FotoFestival.new("孟婆尊神诞")],
    "9-14" => [T_PRIVATE],
    "9-15" => [W_PRIVATE, T_PRIVATE],
    "9-17" => [FotoFestival.new("金龙四大王诞", "犯者遭水厄")],
    "9-19" => [FotoFestival.new("日宫月宫会合", JS_PRIVATE), FotoFestival.new("观世音菩萨诞", JS_PRIVATE)],
    "9-23" => [T_PRIVATE],
    "9-25" => [H_PRIVATE, Y_PRIVATE],
    "9-27" => [D_PRIVATE],
    "9-28" => [R_PRIVATE],
    "9-29" => [T_PRIVATE],
    "9-30" => [FotoFestival.new("药师琉璃光佛诞", "犯者危疾"), HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "10-1" => [S_PRIVATE, FotoFestival.new("民岁腊", DJ_PRIVATE), FotoFestival.new("四天王降", "犯者一年内死")],
    "10-3" => [D_PRIVATE, FotoFestival.new("三茅诞")],
    "10-5" => [FotoFestival.new("下会日", JS_PRIVATE), FotoFestival.new("达摩祖师诞", JS_PRIVATE)],
    "10-6" => [L_PRIVATE, FotoFestival.new("天曹考察", DJ_PRIVATE)],
    "10-8" => [FotoFestival.new("佛涅槃日", "", false, "大忌色欲"), T_PRIVATE],
    "10-10" => [FotoFestival.new("四天王降", "犯者一年内死")],
    "10-11" => [FotoFestival.new("宜戒")],
    "10-14" => [FotoFestival.new("三元降", JS_PRIVATE), T_PRIVATE],
    "10-15" => [W_PRIVATE, FotoFestival.new("三元降", DJ_PRIVATE), FotoFestival.new("下元水府校籍", DJ_PRIVATE), T_PRIVATE],
    "10-16" => [FotoFestival.new("三元降", JS_PRIVATE), T_PRIVATE],
    "10-23" => [Y_PRIVATE, T_PRIVATE],
    "10-25" => [H_PRIVATE],
    "10-27" => [D_PRIVATE, FotoFestival.new("北极紫徽大帝降")],
    "10-28" => [R_PRIVATE],
    "10-29" => [T_PRIVATE],
    "10-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "11-1" => [S_PRIVATE],
    "11-3" => [D_PRIVATE],
    "11-4" => [FotoFestival.new("至圣先师孔子诞", XL_PRIVATE)],
    "11-6" => [FotoFestival.new("西岳大帝诞")],
    "11-8" => [T_PRIVATE],
    "11-11" => [FotoFestival.new("天地仓开日", DJ_PRIVATE), FotoFestival.new("太乙救苦天尊诞", DJ_PRIVATE)],
    "11-14" => [T_PRIVATE],
    "11-15" => [FotoFestival.new("月望", "上半夜犯男死 下半夜犯女死"), FotoFestival.new("四天王巡行", "上半夜犯男死 下半夜犯女死")],
    "11-17" => [FotoFestival.new("阿弥陀佛诞")],
    "11-19" => [FotoFestival.new("太阳日宫诞", "犯者得奇祸")],
    "11-21" => [Y_PRIVATE],
    "11-23" => [FotoFestival.new("张仙诞", "犯者绝嗣"), T_PRIVATE],
    "11-25" => [FotoFestival.new("掠刷大夫降", "犯者遭大凶"), H_PRIVATE],
    "11-26" => [FotoFestival.new("北方五道诞")],
    "11-27" => [D_PRIVATE],
    "11-28" => [R_PRIVATE],
    "11-29" => [T_PRIVATE],
    "11-30" => [HH_PRIVATE, M_PRIVATE, T_PRIVATE],
    "12-1" => [S_PRIVATE],
    "12-3" => [D_PRIVATE],
    "12-6" => [FotoFestival.new("天地仓开日", JS_PRIVATE), L_PRIVATE],
    "12-7" => [FotoFestival.new("掠刷大夫降", "犯者得恶疾")],
    "12-8" => [FotoFestival.new("王侯腊", DJ_PRIVATE), FotoFestival.new("释迦如来成佛之辰"), T_PRIVATE, FotoFestival.new("初旬内戊日，亦名王侯腊", DJ_PRIVATE)],
    "12-12" => [FotoFestival.new("太素三元君朝真")],
    "12-14" => [T_PRIVATE],
    "12-15" => [W_PRIVATE, T_PRIVATE],
    "12-16" => [FotoFestival.new("南岳大帝诞")],
    "12-19" => [Y_PRIVATE],
    "12-20" => [FotoFestival.new("天地交道", "犯者促寿")],
    "12-21" => [FotoFestival.new("天猷上帝诞")],
    "12-23" => [FotoFestival.new("五岳诞降"), T_PRIVATE],
    "12-24" => [FotoFestival.new("司今朝天奏人善恶", "犯者得大祸")],
    "12-25" => [FotoFestival.new("三清玉帝同降，考察善恶", "犯者得奇祸"), H_PRIVATE],
    "12-27" => [D_PRIVATE],
    "12-28" => [R_PRIVATE],
    "12-29" => [FotoFestival.new("华严菩萨诞"), T_PRIVATE],
    "12-30" => [FotoFestival.new("诸神下降，察访善恶", "犯者男女俱亡")]
  }

  OTHER_FESTIVAL = {
    "1-1" => ["弥勒菩萨圣诞"],
    "1-6" => ["定光佛圣诞"],
    "2-8" => ["释迦牟尼佛出家"],
    "2-15" => ["释迦牟尼佛涅槃"],
    "2-19" => ["观世音菩萨圣诞"],
    "2-21" => ["普贤菩萨圣诞"],
    "3-16" => ["准提菩萨圣诞"],
    "4-4" => ["文殊菩萨圣诞"],
    "4-8" => ["释迦牟尼佛圣诞"],
    "4-15" => ["佛吉祥日"],
    "4-28" => ["药王菩萨圣诞"],
    "5-13" => ["伽蓝菩萨圣诞"],
    "6-3" => ["韦驮菩萨圣诞"],
    "6-19" => ["观音菩萨成道"],
    "7-13" => ["大势至菩萨圣诞"],
    "7-15" => ["佛欢喜日"],
    "7-24" => ["龙树菩萨圣诞"],
    "7-30" => ["地藏菩萨圣诞"],
    "8-15" => ["月光菩萨圣诞"],
    "8-22" => ["燃灯佛圣诞"],
    "9-9" => ["摩利支天菩萨圣诞"],
    "9-19" => ["观世音菩萨出家"],
    "9-30" => ["药师琉璃光佛圣诞"],
    "10-5" => ["达摩祖师圣诞"],
    "10-20" => ["文殊菩萨出家"],
    "11-17" => ["阿弥陀佛圣诞"],
    "11-19" => ["日光菩萨圣诞"],
    "12-8" => ["释迦牟尼佛成道"],
    "12-23" => ["监斋菩萨圣诞"],
    "12-29" => ["华严菩萨圣诞"]
  }

  def initialize
  end
end